import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/page";
import "./styles/navbar.css"
import "./styles/category.css"
import "./styles/login.css"
import "./styles/signup.css"
import "./styles/products.css"
import "./styles/cart.css"
import "./styles/orders.css"
import "./styles/profile.css"
import "./styles/paymentpage.css"
import "./styles/address.css"
import "./styles/orderdetail.css"
import "./styles/verifycode.css"
import Providers from "./provider/provider.js";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Freshcart",
  description: "Generated by dev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <Navbar/>
        {children}</Providers>
      </body>
    </html>
  );
}
